#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  yMin,           sensorTouch)
#pragma config(Sensor, dgtl2,  yMax,           sensorTouch)
#pragma config(Sensor, dgtl3,  xMin,           sensorTouch)
#pragma config(Sensor, dgtl4,  xMax,           sensorTouch)
#pragma config(Sensor, dgtl6,  LED1,           sensorDigitalOut)
#pragma config(Sensor, dgtl7,  LED2,           sensorDigitalOut)
#pragma config(Sensor, dgtl8,  LED3,           sensorDigitalOut)
#pragma config(Sensor, dgtl9,  LED4,           sensorDigitalOut)
#pragma config(Sensor, dgtl10, LED5,           sensorDigitalOut)
#pragma config(Sensor, dgtl11, LED6,           sensorDigitalOut)
#pragma config(Motor,  port2,           xMotor,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           yMotor,        tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Code for robot scanner
// Mark Edwardson - V00967010
// Brendan Mackey - V00956501
// Victor Yang - V00961716
// 2021-03-15

void updateDisplay(int counter) {
if(counter >= 8) {
		SensorValue[LED4] = 0;
		counter = counter-8;
	}
	else {
		SensorValue[LED3] = 1;
	}
if(counter >= 4) {
		SensorValue[LED3] = 0;
		counter = counter-4;
	}
	else {
		SensorValue[LED3] = 1;
	}
	if(counter>=2) {
		SensorValue[LED2] = 0;
		counter = counter-2;
	}
	else {
		SensorValue[LED2] = 1;
	}

	if(counter>=1) {
		SensorValue[LED1] = 0;
	}
	else {
		SensorValue[LED1] = 1;
	}
	return;
}

int lightSensorValue = 0;
int counter = 0;
int data[20] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
//int timeValue = 0,0;
task main() {
	SensorValue[LED1] = 1;
	SensorValue[LED2] = 1;
	SensorValue[LED3] = 1;
	SensorValue[LED4] = 1;
	SensorValue[LED5] = 1;
	SensorValue[LED6] = 1;
	int threshhold = 3400;
	int nudgeInterval = 1400;
	int sensorSleep = 4000;
	int i = 0;

/*clearTimer(T1);
//time1[T1];
motor[yMotor] = 50;
while(SensorValue[yMax] == 0) {
	timeValue = time1[T1];
}*/

//homing
	while(SensorValue[xMin] == 0) {
		motor[xMotor] = -50;
	}
	motor[xMotor] = 0;

	while(SensorValue[yMin] == 0) {
		motor[yMotor] = -50;
	}
	motor[yMotor] = 0;
//main program loop for scanning
	while(SensorValue[yMax] == 0) {

		//scan positive x
		while(SensorValue[xMax] == 0) {
			motor[xMotor] = 50;
			lightSensorValue = SensorValue[lightSensor];
			if(lightSensorValue > threshhold) {
				SensorValue[LED6] = 0;
				counter++;
				data[i] = 1;
				updateDisplay(counter);
				wait1Msec(sensorSleep);
			}
			else {
				SensorValue[LED6] = 1;
			}
		}
		motor[xMotor] = 0;

		//nudge y
		motor[yMotor] = 50;
		wait1Msec(nudgeInterval);
		motor[yMotor] = 0;
		i++;
		// scan negative x
		while(SensorValue[xMin] == 0) {
			motor[xMotor] = -50;
			lightSensorValue = SensorValue[lightSensor];
			if(lightSensorValue > threshhold) {
				counter++;
				data[i] = 1;
				updateDisplay(counter);
				SensorValue[LED6] = 0;

				wait1Msec(sensorSleep);
			}
			else {
				SensorValue[LED6] = 1;
			}
		}
		motor[xMotor] = 0;
		//nudge y
		motor[yMotor] = 50;
		wait1Msec(nudgeInterval);
		motor[yMotor] = 0;
		i++;
	}//break main scanning loop


	// scan one more x before homing
	/*while(SensorValue[xMax] == 0) {
		motor[xMotor] = 50;
			motor[xMotor] = 50;
			lightSensorValue = SensorValue[lightSensor];
			if(lightSensorValue > threshhold) {
				SensorValue[LED6] = 1;
				counter++;
				updateDisplay(counter);
				wait1Msec(sensorSleep);
			}
			else {
				SensorValue[LED6] = 0;
			}
	}*/
	motor[xMotor] = 0;

	//homing
	while(SensorValue[xMin] == 0) {
		motor[xMotor] = -50;
	}
	motor[xMotor] = 0;

	while(SensorValue[yMin] == 0) {
		motor[yMotor] = -50;
	}
	motor[yMotor] = 0;
	//IDLE - program end





	i = 0;
	counter = 0;
	updateDisplay(counter);
	//SECOND SCAN
	while(SensorValue[yMax] == 0) {

		//scan positive x
	if(data[i] == 1) {
		if(SensorValue[xMin] == 1) {
		while(SensorValue[xMax] == 0) {
			motor[xMotor] = 50;
			lightSensorValue = SensorValue[lightSensor];
			if(lightSensorValue > threshhold) {
				SensorValue[LED6] = 0;
				counter++;
				data[i] = 1;
				updateDisplay(counter);
				wait1Msec(sensorSleep);
			}
			else {
				SensorValue[LED6] = 1;
			}
		}
		motor[xMotor] = 0;
}
else {
		// scan negative x
		while(SensorValue[xMin] == 0) {
			motor[xMotor] = -50;
			lightSensorValue = SensorValue[lightSensor];
			if(lightSensorValue > threshhold) {
				counter++;
				data[i] = 1;
				updateDisplay(counter);
				SensorValue[LED6] = 0;

				wait1Msec(sensorSleep);
			}
			else {
				SensorValue[LED6] = 1;
			}
		}
	}}
		motor[xMotor] = 0;
		//nudge y
		motor[yMotor] = 50;
		wait1Msec(nudgeInterval);
		motor[yMotor] = 0;
		i++;
	}//break main scanning loop


	// scan one more x before homing
	while(SensorValue[xMax] == 0) {
		motor[xMotor] = 50;
			motor[xMotor] = 50;
			lightSensorValue = SensorValue[lightSensor];
			if(lightSensorValue > threshhold) {
				SensorValue[LED6] = 1;
				counter++;
				updateDisplay(counter);
				wait1Msec(sensorSleep);
			}
			else {
				SensorValue[LED6] = 0;
			}
	}
	motor[xMotor] = 0;

	//homing
	while(SensorValue[xMin] == 0) {
		motor[xMotor] = -50;
	}
	motor[xMotor] = 0;

	while(SensorValue[yMin] == 0) {
		motor[yMotor] = -50;
	}
	motor[yMotor] = 0;


	i = 0;
	counter = 0;
	updateDisplay(counter);
//	int data[20] = {1,0,1,1,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0};

	//SECOND SCAN
	while(SensorValue[yMax] == 0) {

		//scan positive x
	if(data[i] == 1) {
		if(SensorValue[xMin] == 1) {
		while(SensorValue[xMax] == 0) {
			motor[xMotor] = 50;
			lightSensorValue = SensorValue[lightSensor];
			if(lightSensorValue > threshhold) {
				SensorValue[LED6] = 0;
				counter++;
				data[i] = 1;
				updateDisplay(counter);
				wait1Msec(sensorSleep);
			}
			else {
				SensorValue[LED6] = 1;
			}
		}
		motor[xMotor] = 0;
}
else {
		// scan negative x
		while(SensorValue[xMin] == 0) {
			motor[xMotor] = -50;
			lightSensorValue = SensorValue[lightSensor];
			if(lightSensorValue > threshhold) {
				counter++;
				data[i] = 1;
				updateDisplay(counter);
				SensorValue[LED6] = 0;

				wait1Msec(sensorSleep);
			}
			else {
				SensorValue[LED6] = 1;
			}
		}
	}}
		motor[xMotor] = 0;
		//nudge y
		motor[yMotor] = 50;
		wait1Msec(nudgeInterval);
		motor[yMotor] = 0;
		i++;
	}//break main scanning loop


	// scan one more x before homing
	while(SensorValue[xMax] == 0) {
		motor[xMotor] = 50;
			motor[xMotor] = 50;
			lightSensorValue = SensorValue[lightSensor];
			if(lightSensorValue > threshhold) {
				SensorValue[LED6] = 1;
				counter++;
				updateDisplay(counter);
				wait1Msec(sensorSleep);
			}
			else {
				SensorValue[LED6] = 0;
			}
	}
	motor[xMotor] = 0;

	//homing
	while(SensorValue[xMin] == 0) {
		motor[xMotor] = -50;
	}
	motor[xMotor] = 0;

	while(SensorValue[yMin] == 0) {
		motor[yMotor] = -50;
	}
	motor[yMotor] = 0;
	//IDLE - program end

}
